<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Malay Peninsula Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="X1MVAPD-UFT01"><DocLocation><![CDATA[C:\Users\kathiraven\Desktop\Test UFT\TestFunctional]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[TestFunctional]]></DName>
<Res><![CDATA[Res14]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:00]]></Time>
<TimeTick>1655712900</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:00]]></Time>
<TimeTick>1655712900</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[CTOS Connect – Knowledge]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:06]]></Time>
<TimeTick>1655712906</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[CTOS Connect – Knowledge.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://www.google.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:06]]></Time>
<TimeTick>1655712906</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" Source="Action1" SourceLine="8" >
<Disp><![CDATA[CTOS Connect – Knowledge.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:07]]></Time>
<TimeTick>1655712907</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Search.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Functional Testing"]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:07]]></Time>
<TimeTick>1655712907</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Search.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Google Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:07]]></Time>
<TimeTick>1655712907</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Google Search.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="16" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Functional Testing - Google]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:09]]></Time>
<TimeTick>1655712909</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Images.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:09]]></Time>
<TimeTick>1655712909</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="24" Source="Action1" SourceLine="12" >
<Disp><![CDATA[Images.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Videos.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:09]]></Time>
<TimeTick>1655712909</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="27" Source="Action1" SourceLine="13" >
<Disp><![CDATA[Videos.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[News.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:11]]></Time>
<TimeTick>1655712911</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="30" Source="Action1" SourceLine="14" >
<Disp><![CDATA[News.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Books.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:11]]></Time>
<TimeTick>1655712911</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="33" Source="Action1" SourceLine="15" >
<Disp><![CDATA[Books.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[More.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:12]]></Time>
<TimeTick>1655712912</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="36" Source="Action1" SourceLine="16" >
<Disp><![CDATA[More.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Maps Shopping Flights.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Shopping"]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:15]]></Time>
<TimeTick>1655712915</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="39" Source="Action1" SourceLine="18" >
<Disp><![CDATA[Maps Shopping Flights.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[More_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:17]]></Time>
<TimeTick>1655712917</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="42" Source="Action1" SourceLine="20" >
<Disp><![CDATA[More_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Videos News Books Flights.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Books"]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:20]]></Time>
<TimeTick>1655712920</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="45" Source="Action1" SourceLine="22" >
<Disp><![CDATA[Videos News Books Flights.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Any view.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:21]]></Time>
<TimeTick>1655712921</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" Source="Action1" SourceLine="24" >
<Disp><![CDATA[Any view.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Maps Shopping Flights.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Preview and full view"]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:23]]></Time>
<TimeTick>1655712923</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="51" Source="Action1" SourceLine="26" >
<Disp><![CDATA[Maps Shopping Flights.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Preview and full view.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:25]]></Time>
<TimeTick>1655712925</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="54" Source="Action1" SourceLine="28" >
<Disp><![CDATA[Preview and full view.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Maps Shopping Flights.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Full view"]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:25]]></Time>
<TimeTick>1655712925</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="57" Source="Action1" SourceLine="29" >
<Disp><![CDATA[Maps Shopping Flights.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:25]]></Time>
<TimeTick>1655712925</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="60" Source="Action1" SourceLine="30" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="23" Source="Action1" SourceLine="12" >
<Disp><![CDATA[Functional Testing - Google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[CTOS Connect – Knowledge.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:26]]></Time>
<TimeTick>1655712926</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="62" Source="Action1" SourceLine="31" >
<Disp><![CDATA[CTOS Connect – Knowledge.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:27]]></Time>
<TimeTick>1655712927</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:27]]></Time>
<TimeTick>1655712927</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="66" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="65" status="Passed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[CTOS Connect – Knowledge.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://www.google.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:33]]></Time>
<TimeTick>1655712933</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="68" Source="Action1" SourceLine="8" >
<Disp><![CDATA[CTOS Connect – Knowledge.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:35]]></Time>
<TimeTick>1655712935</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Search.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Non Functional Testing"]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:35]]></Time>
<TimeTick>1655712935</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="72" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Search.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Google Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:35]]></Time>
<TimeTick>1655712935</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="75" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Google Search.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="71" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Functional Testing - Google]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:37]]></Time>
<TimeTick>1655712937</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Images.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:37]]></Time>
<TimeTick>1655712937</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="79" Source="Action1" SourceLine="12" >
<Disp><![CDATA[Images.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Videos.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:39]]></Time>
<TimeTick>1655712939</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="82" Source="Action1" SourceLine="13" >
<Disp><![CDATA[Videos.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[News.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:41]]></Time>
<TimeTick>1655712941</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="85" Source="Action1" SourceLine="14" >
<Disp><![CDATA[News.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Books.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:41]]></Time>
<TimeTick>1655712941</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="88" Source="Action1" SourceLine="15" >
<Disp><![CDATA[Books.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[More.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:42]]></Time>
<TimeTick>1655712942</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="91" Source="Action1" SourceLine="16" >
<Disp><![CDATA[More.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Maps Shopping Flights.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Shopping"]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:44]]></Time>
<TimeTick>1655712944</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="94" Source="Action1" SourceLine="18" >
<Disp><![CDATA[Maps Shopping Flights.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[More_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:47]]></Time>
<TimeTick>1655712947</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="97" Source="Action1" SourceLine="20" >
<Disp><![CDATA[More_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Videos News Books Flights.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Books"]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:50]]></Time>
<TimeTick>1655712950</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="100" Source="Action1" SourceLine="22" >
<Disp><![CDATA[Videos News Books Flights.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Any view.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:51]]></Time>
<TimeTick>1655712951</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="103" Source="Action1" SourceLine="24" >
<Disp><![CDATA[Any view.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Maps Shopping Flights.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Preview and full view"]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:53]]></Time>
<TimeTick>1655712953</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="106" Source="Action1" SourceLine="26" >
<Disp><![CDATA[Maps Shopping Flights.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Preview and full view.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:55]]></Time>
<TimeTick>1655712955</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="109" Source="Action1" SourceLine="28" >
<Disp><![CDATA[Preview and full view.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Maps Shopping Flights.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Full view"]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:55]]></Time>
<TimeTick>1655712955</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="112" Source="Action1" SourceLine="29" >
<Disp><![CDATA[Maps Shopping Flights.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:56]]></Time>
<TimeTick>1655712956</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="115" Source="Action1" SourceLine="30" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="78" Source="Action1" SourceLine="12" >
<Disp><![CDATA[Functional Testing - Google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[CTOS Connect – Knowledge.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/20/2022 - 16:15:57]]></Time>
<TimeTick>1655712957</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="117" Source="Action1" SourceLine="31" >
<Disp><![CDATA[CTOS Connect – Knowledge.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="12" status="Passed" Source="Action1" SourceLine="8" >
<Disp><![CDATA[CTOS Connect – Knowledge]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="6/20/2022 - 16:14:59" eTime="6/20/2022 - 16:15:57" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="6/20/2022 - 16:14:58" eTime="6/20/2022 - 16:15:57" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test TestFunctional Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>